### PR TITLE
feat: implement midi blocks

### PR DESCRIPTION
**Pull request by Shrekfied**

### CODE REVIEW

**Comment by DavidBuchanan314** [comment]
Thanks for the contribution, what do you mean by do nothing? (could you give an example?)

**Comment by DavidBuchanan314** [comment]
What are the midi blocks exactly? e.g. how is `music_midiPlayDrumForBeats` different from `music_playDrumForBeats`? Are they leftovers from Scratch 2.0?

**Comment by Shrekfied** [comment]
> What are the midi blocks exactly? e.g. how is `music_midiPlayDrumForBeats` different from `music_playDrumForBeats`? Are they leftovers from Scratch 2.0?

According to the comments in the scratch-vm repository, they allow you to play standard MIDI instruments by number and probably exist for backwards compatibility with Scratch 1.4.

**Comment by DavidBuchanan314** [comment]
The Answer block takes no arguments etc., so that's all it takes to implement it. It's fully working!

I've removed the midi blocks (but kept the rest of the music stuff) because I only want Boiga to be able to create things that can also be created using the official Scratch GUI.

**Comment by DavidBuchanan314** [comment]
I added an example for the music stuff, so you can see the `GetTempo()` reporter in action https://github.com/DavidBuchanan314/boiga/blob/main/examples/music.py

**Pull request merged**
